version: '3.3'

services:
  mongo-test:
    image: mongo:4.4
    container_name: mongo-test
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: p@55w0rd
    ports:
      - 27017:27017