name: CORE PORFOLIO CI
on: [push]

defaults:
  run:
    working-directory: ./

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with: 
          node-version: 16
          cache: 'npm'

      - name: Install
        shell: bash
        run: npm ci --legacy-peer-deps

      - name: Run unit test
        shell: bash
        run: npm run test
  
  e2e-test:
    runs-on: ubuntu-latest

    container:
      image: node:16

    services:
      mongo-e2e:
        image: mongo:4.4
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: test
          MONGO_INITDB_ROOT_PASSWORD: p@55w0rd
      
      postgres-e2e:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: tester
          POSTGRES_PASSWORD: password
          POSTGRES_DATABASE: test
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        shell: bash
        run: npm ci --legacy-peer-deps

      - name: Run e2e test
        shell: bash
        run: npm run test:e2e
        env:
          MONGO_DB_NAME: test
          MONGO_URL: mongodb://test:p%4055w0rd@localhost:27017/test?retryWrites=true&writeConcern=majority
          POSTGRES_USER: tester
          POSTGRES_PASSWORD: password
