name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install YARN
        shell: bash
        run: npm i -g yarn

      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install packages
        shell: bash
        run: yarn install

      - name: Run tests
        shell: bash
        run: yarn test

      - name: Install Railway
        shell: bash
        run: npm install -g @railway/cli

      - name: Deploy
        run: railway up --service core.portfolio
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
